apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: lihx8y9uq-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: lihx8y9uq-nodejs 
  name: lihx8y9uq-nodejs
spec:
  port:
    targetPort: 3001 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: lihx8y9uq-nodejs
    weight: 100 
