apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: lihx8y9uq-nodejs 
  janus-idp.io/tekton: lihx8y9uq-nodejs
  backstage.io/kubernetes-id: lihx8y9uq-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: lihx8y9uq-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml